### ISSUE TITLE
Return value of Pdp\Converter::idnToAscii() must be of the type string, boolean returned

### ISSUE THREAD

**Issue by spagu** [jeremykendall/php-domain-parser#230] opened 2018-11-06 03:18 UTC
## Issue summary

does not work

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| Pdp version | 5.3.0 |
| PHP version | 7.2 |
| OS Platform | BSD |

## Standalone code, or other way to reproduce the problem

$manager = new Manager(new Cache(), new CurlHttpClient());
$rules = $manager->getRules();

### Expected result
no error

### Actual result
Type: TypeError
Message: Return value of Pdp\Converter::idnToAscii() must be of the type string, boolean returned
File: /project/vendor/jeremykendall/php-domain-parser/src/IDNAConverterTrait.php
Line: 88

**Comment by nyamsprod** [comment] 2018-11-06 07:58
@spagu thanks for your issue report but alas I fail to reproduce your error:
- with the current stable release 
- with the develop branch which contains bugfixes for this particular piece of code

Could you please try using the develop branch to see if you still have the same issue thanks in advance.  The following snippet should improve detecting where the bug is 

```php
use Pdd\Manager;
use Pdd\Rules;
$rules = Rules::createFromPath(Manager::PSL_URL);
```
If this snippet works then it means that the issue is with how the `CurlHttpClient` is setup. Some improvement will be landing on the next release to improve the `CurlHttpClient` adapter default setup but you can override them easily by providing your own curl options.

**Comment by nyamsprod** [comment] 2018-11-06 20:05
mmmh seems that the downloaded files is corrupted somehow :thinking: 
Can you download the PSL directly from your browser and feed it to the Converter class like below:

```php
use Pdp\Converter;

$content = file_get_contents('/path/saved/public-suffix-list.tld);
$converter = new Converter();
$res = $converter->convert($content);
```
If you still get an error then try with the develop branch.

Sorry for asking but I can not reproduce the error with my setup. I've tested on two different OS (Windows and Linux) and I get not error in both setup.

**Comment by spagu** [comment] 2018-11-06 21:44
```
Type: TypeError
Message: Return value of Pdp\Converter::idnToAscii() must be of the type string, boolean returned
File: /project/vendor/jeremykendall/php-domain-parser/src/IDNAConverterTrait.php
Line: 88
```
this fails only when doing : $res = $converter->convert($content);

Notice: Undefined index: errors in /project/vendor/jeremykendall/php-domain-parser/src/IDNAConverterTrait.php on line 87

**Comment by nyamsprod** [comment] 2018-11-06 21:50
Ok made some digging on php.net bug database and it seems you are running into this issue since you are on BSD :( https://bugs.php.net/bug.php?id=74276

**Comment by spagu** [comment] 2018-11-07 14:46
I have added output check for false in IDNAConverterTrait.php / function idnToAscii
```
        if ( !$arr['errors'] && false !== $output ) {
            return $output;
        }
```
this somehow does not generate problem and idn names works. But I am not sure on impact.

**Comment by nyamsprod** [comment] 2018-11-07 14:56
I thought about adding this check but it defeat completely the use of the `$arr` array and also it may skip valid public suffix on BSD .... a better alternative would be to create a special Exception for this case IMHO and tell the user that the `ext-intl` extension is not correctly installed at least not from PHP point of view.

**Comment by nyamsprod** [comment] 2018-11-16 09:29
@spagu I choose to throw an `UnexpectedValueException` from PHP SPL Exception directly and not make the Exception part of the package Exception subnamespace to clearly mark that it is not a package exception per se but rather a PHP/Intl misconfiguration and that resolution should be taken at another level. Is that ok for you ?

**Comment by nyamsprod** [comment] 2018-11-22 18:56
version 5.4.0 is released with the bug fix implemented

**Closed by nyamsprod** 2018-11-22 18:56 UTC
Labels: bug, question, version 5.0
